### ISSUE TITLE
Asynchronous deserialization with Streams

### ISSUE THREAD

**Issue by Leptopoda** [tnc1997/dart-xml-serializable#38]
The xml lib has very good Stream support.
It would be great if the generated code would also make use of that.

This would probably improve performance as the data could be deserialized asynchronously as it arrives.

**Comment by tnc1997** [comment]
Hi @Leptopoda, thank you very much for your feature suggestion. This is something that I have considered in the past, however it does add quite a bit of complexity to deserialization. There are other more straightforward features that I would like implementing before reviewing support for streams.

**Comment by Leptopoda** [comment]
Sad to hear that you are no longer planning to implement this.
Can you please let us know what your reasoning is? Is it impossible or are you just no longer considering this in scope for your package?
I don't think that I'd be working on this in the near future but are you open for a PR implementing this?

**Comment by tnc1997** [comment]
Hi @Leptopoda, hope you're well! It has been over a year since the feature request was submitted and it has not garnered any further discussion. I also believe that there is a significant amount of complexity involved in supporting streams in the source code generated by `xml_serializable`. I am open to discussing this feature request in more detail especially regarding the ways that support for streams could be implemented.
